# Generated by Django 2.1.7 on 2019-03-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_person',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_person',
            field=models.ManyToManyField(to='task_manager.Employee'),
        ),
    ]
