# Generated by Django 2.1.7 on 2019-03-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_person',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task_manager.Employee'),
            preserve_default=False,
        ),
    ]
