# Generated by Django 2.1.7 on 2019-03-12 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('task_manager', '0003_auto_20190311_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_developer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.Employee'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
