# Generated by Django 2.1.7 on 2019-03-13 12:29

from django.db import migrations, models
import task_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_auto_20190313_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_person',
            field=models.CharField(default='', max_length=200, verbose_name=task_manager.models.Employee),
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.CharField(default='', max_length=200, verbose_name=task_manager.models.Project),
        ),
    ]
