# Generated by Django 2.1.7 on 2019-03-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_auto_20190313_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_manager.Employee'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ManyToManyField(to='task_manager.Project'),
        ),
    ]
